(function(){
'use strict';
let data=NavStore.load(),current='all',query='';
const $=id=>document.getElementById(id);
function visibleSites(){return data.sites.filter(s=>s.visibility!==false&&s.status!=='dead')}
function renderNav(){const counts=new Map();visibleSites().forEach(s=>counts.set(s.category,(counts.get(s.category)||0)+1));const items=[{id:'all',name:'全部网站',icon:'▦',count:visibleSites().length}];if(data.settings.showFavorites)items.push({id:'fav',name:'我的收藏',icon:'★',count:data.favorites.length});data.categories.slice().sort((a,b)=>a.order-b.order).forEach(c=>items.push({...c,count:counts.get(c.id)||0}));$('categoryNav').innerHTML=items.map(x=>'<button class="nav-btn '+(current===x.id?'active':'')+'" data-id="'+x.id+'"><span>'+x.icon+'</span><span>'+escapeHtml(x.name)+'</span><span class="count">'+x.count+'</span></button>').join('');$('categoryNav').querySelectorAll('button').forEach(b=>b.onclick=()=>{current=b.dataset.id;query='';$('searchInput').value='';render();closeMenu()})}
function render(){data=NavStore.load();const cats=new Map(data.categories.map(c=>[c.id,c]));let sites=visibleSites();if(current==='fav')sites=sites.filter(s=>data.favorites.includes(s.id));else if(current!=='all')sites=sites.filter(s=>s.category===current);if(query){const q=query.toLowerCase();sites=sites.filter(s=>(s.name+' '+s.desc+' '+s.url).toLowerCase().includes(q))}const title=query?'搜索结果':current==='all'?'全部网站':current==='fav'?'我的收藏':(cats.get(current)?.name||'全部网站');$('headerLabel').textContent=title;$('viewTitle').textContent=title;$('viewSubtitle').textContent=query?'找到 '+sites.length+' 个匹配网站':'共 '+sites.length+' 个可用入口';$('siteGrid').innerHTML=renderSitesHtml(sites);bindFavoriteButtons();$('searchPanel').style.display=data.settings.showSearch?'flex':'none';$('themeBtn').style.display=data.settings.showThemeToggle?'grid':'none';$('clock').style.display=(data.settings.showTime||data.settings.showDate)?'block':'none';$('stats').style.display=data.settings.showStats?'flex':'none';$('stats').innerHTML='<span class="stat"><b>'+visibleSites().length+'</b>网站</span><span class="stat"><b>'+data.categories.length+'</b>分类</span>';renderNav()}
function renderSitesHtml(sites){if(!sites.length)return '<div class="empty">没有符合条件的网站</div>';if(current!=='all'||query)return sites.map(siteCard).join('');return data.categories.slice().sort((a,b)=>a.order-b.order).map(c=>{const group=sites.filter(s=>s.category===c.id);if(!group.length)return '';return '<section class="category-group"><div class="category-head"><span class="category-icon">'+escapeHtml(c.icon)+'</span><h2>'+escapeHtml(c.name)+'</h2><span class="category-count">'+group.length+' 个网站</span></div><div class="category-grid">'+group.map(siteCard).join('')+'</div></section>'}).join('')}
function siteCard(s){const fav=data.favorites.includes(s.id),desc=data.settings.showDescriptions?'<div class="site-desc">'+escapeHtml(s.desc||s.url)+'</div>':'',status=s.status==='review'?'<span class="status">待复核</span>':s.status==='redirect'?'<span class="status">已重定向</span>':'';return '<a class="site-card" href="'+escapeAttr(s.finalUrl||s.url)+'" target="_blank" rel="noopener"><div class="site-icon">'+escapeHtml(s.icon||domainInitial(s.url))+'</div><div><div class="site-name">'+escapeHtml(s.name)+'</div>'+desc+'</div><button class="fav-btn '+(fav?'active':'')+'" data-id="'+s.id+'" title="'+(fav?'取消收藏':'加入收藏')+'">★</button>'+status+'</a>'}
function bindFavoriteButtons(){$('siteGrid').querySelectorAll('.fav-btn').forEach(btn=>btn.onclick=e=>{e.preventDefault();e.stopPropagation();toggleFavorite(btn.dataset.id)})}
function toggleFavorite(id){const set=new Set(data.favorites);set.has(id)?set.delete(id):set.add(id);data.favorites=[...set];NavStore.save(data);render()}
function doSearch(){const value=$('searchInput').value.trim(),engine=$('engineSelect').value;if(!value)return;if(engine==='local'){query=value;current='all';render()}else{const item=data.searchEngines.find(e=>e.id===engine);if(item)window.open(item.urlTemplate.replace('{q}',encodeURIComponent(value)),'_blank','noopener')}}
function renderEngines(){$('engineSelect').innerHTML=data.searchEngines.map(e=>'<option value="'+e.id+'">'+escapeHtml(e.icon+' '+e.name)+'</option>').join('')}
function updateClock(){const now=new Date(),opt={hour:'2-digit',minute:'2-digit',hour12:false};if(data.settings.showSeconds)opt.second='2-digit';$('clockTime').textContent=data.settings.showTime?now.toLocaleTimeString('zh-CN',opt):'';$('clockDate').textContent=data.settings.showDate?now.toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}):''}
function closeMenu(){$('sidebar').classList.remove('open');$('backdrop').classList.remove('open')}
function domainInitial(url){try{return new URL(url).hostname.replace(/^www\./,'')[0].toUpperCase()}catch{return '?'}}
function escapeHtml(v){const d=document.createElement('div');d.textContent=String(v||'');return d.innerHTML}
function escapeAttr(v){return escapeHtml(v).replace(/"/g,'&quot;')}
$('searchBtn').onclick=doSearch;$('searchInput').onkeydown=e=>{if(e.key==='Enter')doSearch()};$('searchInput').oninput=e=>{if($('engineSelect').value==='local'){query=e.target.value.trim();current='all';render()}};$('menuBtn').onclick=()=>{$('sidebar').classList.add('open');$('backdrop').classList.add('open')};$('backdrop').onclick=closeMenu;$('themeBtn').onclick=()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark';localStorage.setItem('nav_theme',dark?'light':'dark')};window.addEventListener('storage',e=>{if(e.key===NavStore.STORAGE_KEY){data=NavStore.load();renderEngines();render()}});document.documentElement.dataset.theme=localStorage.getItem('nav_theme')||'light';renderEngines();render();updateClock();setInterval(updateClock,1000);
})();
